name: go_router_tabs
description: A wrapper around the go_router package that provides the current sub-route index of a ShellRoute and the direction user came from based on the previous index.
version: 0.1.0
homepage: https://github.com/JakesMD/flutter_go_router_tabs
screenshots:
  - description: 'This is a preview animation of a web app navigating between tabs using this package.'
    path: screenshots/preview.gif

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
