name: go_router_tabs
description: A go_router package add-on to improve tabbed navigation, featuring a special ShellRoute that provides both the selected navigation item index and transition direction.
version: 0.6.0
homepage: https://github.com/JakesMD/flutter_go_router_tabs
screenshots:
  - description: "An example web app navigating between tabs using this package."
    path: screenshots/screenshot.png
  - description: "An animation of a web app navigating between tabs using this package."
    path: screenshots/preview.gif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
